//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;



	public class Conversion
	{
		public Convert factor;
		private float workWidth = 1434;
		private float workHeight = 539/2;
		public Conversion (float screenHeight, float screenWidth)
		{
		//ssssss
			factor = new Convert(screenHeight/2, screenWidth/2);
		}

		public Vector3 makeFixedPoint(Vector3 screenPoint){
			float xWorkDist = workWidth - screenPoint.x;

			float xRatio = 1- xWorkDist / workWidth;
			Debug.Log (xRatio);
			float xFixed = factor.camHeight - xRatio * factor.camHeight;

			float yWorkDist = workHeight - screenPoint.y;
			float yRatio = 1-yWorkDist / workHeight;
			float yFixed = factor.camHeight - yRatio * factor.camHeight;

			Vector3 fixedPoint = new Vector3 (xFixed, yFixed, 0);
			return fixedPoint;
		
		}
	}


